site_name = 'Your Site Name'
site_secret_key = 'your-secret-key-here'
site_url = 'http://localhost:5000/'
site_database_uri = 'sqlite:///data.db'
site_uploads_folder = 'path-to-root-folder/static/uploads'
site_description = 'CMS'
site_keywords = 'CMS'
site_css = 'frontend/style.css'
admin_thumbnail_width = 200
admin_thumbnail_height = 200
thumbnail_width = 600
thumbnail_height = 400
medium_thumbnail_width = 1200
medium_thumbnail_height = 900
powered_by_text = ['Your Name']
powered_by_link = ['http://yoursite.com']
editable_thumbnails = True
media_overview_sortable = False
allowed_media_extensions = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'mov', 'mp4', 'webm', 'ogg', 'flv']);
